data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.coco_dataset
        class: CoCoDataset
        CoCoDataset:
          image_size: 416
          image_dir: '''../efficient_det_pytorch/dataset/birdview_vehicles/val'''
          label_path: '''../efficient_det_pytorch/dataset/birdview_vehicles/annotations/instances_val.json'''
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      batch_size: 16
      shuffle: False
      drop_last: False
      pin_memory: True
      num_workers: 12
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.model
  class: Model
  Model:
    in_channels: 3
    num_classes: 2
    iou_threshold: 0.5
    score_threshold: 0.3
    anchors: [
      [[116.48, 91.52], [158.08, 199.68], [374.4, 324.48]],  # S = 13
      [[29.12, 62.4 ], [62.4, 45.76], [58.24, 120.64]],  # S = 26
      [[8.32, 12.48], [16.64, 29.12], [33.28, 24.96]],  # S = 52
    ]

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      mAP:
        module: flame.handlers.metrics.mean_average_precision.evaluator
        class: Evaluator
        Evaluator:
          eval_fn:
            module: flame.handlers.metrics.mean_average_precision.mean_average_precision
            class: MeanAveragePrecision
            MeanAveragePrecision:
              classes:
                large-vehicle: 0
                small-vehicle: 1
              iou_threshold: 0.5
              method: '''every_point_interpolation'''
          output_transform: 'lambda x: (x[0], x[1])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/birdview_vehicles/2110142139/best_model_19_loss=-0.9154.pt'''
    mode: '''test'''

predictor:
  module: flame.handlers.region_predictor
  class: RegionPredictor
  RegionPredictor:
    evaluator_name: '''engine'''
    output_dir: '''checkpoint/birdview_vehicles/2110142139/best_model_19_loss=-0.9154/valid/'''
    imsize: 416
    classes:
      large-vehicle: [[128, 0, 0], 0]  # color, class_idx, area_threshold
      small-vehicle: [[0, 128, 0], 1]
    output_transform: 'lambda x: (x[0], x[-1])'

engine:
  module: flame.core.engine.evaluator
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
