data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.labelme_dataset
        class: LabelmeDataset
        LabelmeDataset:
          image_size: 416
          dirnames:
            - '''/media/phongpx/New Volume1/Đồ án TN/test_dataset/'''
          image_patterns: ['''*.jpg''', '''*.JPG''']
          label_patterns: ['''*.json''']
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          classes:
            capacitor: 0
            diode: 1
            IC: 2
            resistor: 3
            transistor: 4
      batch_size: 2
      shuffle: False
      num_workers: 2
      pin_memory: True
      drop_last: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.model
  class: Model
  Model:
    in_channels: 3
    num_classes: 5
    iou_threshold: 0.2
    score_threshold: 0.2
    anchors: [
      [[116.48, 91.52], [158.08, 199.68], [374.4, 324.48]],  # S = 13
      [[29.12, 62.4 ], [62.4, 45.76], [58.24, 120.64]],  # S = 26
      [[8.32, 12.48], [16.64, 29.12], [33.28, 24.96]],  # S = 52
    ]

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      mAP:
        module: flame.handlers.metrics.mean_average_precision.evaluator
        class: Evaluator
        Evaluator:
          eval_fn:
            module: flame.handlers.metrics.mean_average_precision.mean_average_precision
            class: MeanAveragePrecision
            MeanAveragePrecision:
              classes:
                capacitor: 0
                diode: 1
                IC: 2
                resistor: 3
                transistor: 4
              iou_threshold: 0.5
              method: '''every_point_interpolation'''
          output_transform: 'lambda x: (x[0], x[1])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/best_model_59_loss=-0.9466.pt'''
    mode: '''test'''

predictor:
  module: flame.handlers.region_predictor
  class: RegionPredictor
  RegionPredictor:
    evaluator_name: '''engine'''
    output_dir: '''checkpoint/best_model_59_loss=-0.9466/'''
    imsize: 416
    classes:
      capacitor: [[128, 0, 0], 0]
      diode: [[0, 128, 0], 1]
      IC: [[128, 128, 0], 2]
      resistor: [[0, 0, 128], 3]
      transistor: [[128, 0, 128], 4]
    output_transform: 'lambda x: (x[0], x[-1])'

engine:
  module: flame.core.engine.evaluator
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
