data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.labelme_dataset
        class: LabelmeDataset
        LabelmeDataset:
          imsize: 416
          dirnames:
            - '''/extdata/ocr/phungpx/projects/PHUNGPX/semantic_segmentation_pytorch/dataset/VEHICLE_REGISTRATION/test/'''
          image_patterns: ['''*.jpg''', '''*.png''', '''*.jpeg''', '''*.JPG''', '''*.PNG''', '''*.JPEG''']
          label_patterns: ['''*.json''']
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          classes:
            DKX_BACK_TYPE_1: 0
            DKX_TYPE_1: 1
            DKX_BACK_TYPE_2: 2
            DKX_TYPE_2: 3
            DKX_BACK_TYPE_3: 4
            DKX_TYPE_3: 5
            DKX_BACK_TYPE_5: 6
            DKX_FRONT_TYPE_5: 7
          S: [13, 26, 52]  # imsize // 32, imsize // 16, imsize // 8
          anchors: [
            [[116.48, 91.52], [158.08, 199.68], [374.4, 324.48]],  # S = 13
            [[29.12, 62.4 ], [62.4, 45.76], [58.24, 120.64]],  # S = 26
            [[8.32, 12.48], [16.64, 29.12], [33.28, 24.96]],  # S = 52
          ]
      batch_size: 16
      shuffle: False
      num_workers: 12
      pin_memory: True
      drop_last: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.model
  class: Model
  Model:
    in_channels: 3
    num_classes: 23
    iou_threshold: 0.5
    score_threshold: 0.2
    anchors: [
      [[116.48, 91.52], [158.08, 199.68], [374.4, 324.48]],  # S = 13
      [[29.12, 62.4 ], [62.4, 45.76], [58.24, 120.64]],  # S = 26
      [[8.32, 12.48], [16.64, 29.12], [33.28, 24.96]],  # S = 52
    ]

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      mAP:
        module: flame.handlers.metrics.mean_average_precision.evaluator
        class: Evaluator
        Evaluator:
          eval_fn:
            module: flame.handlers.metrics.mean_average_precision.mean_average_precision
            class: MeanAveragePrecision
            MeanAveragePrecision:
              classes:
                DKX_BACK_TYPE_1: 0
                DKX_TYPE_1: 1
                DKX_BACK_TYPE_2: 2
                DKX_TYPE_2: 3
                DKX_BACK_TYPE_3: 4
                DKX_TYPE_3: 5
                DKX_BACK_TYPE_5: 6
                DKX_FRONT_TYPE_5: 7
              iou_threshold: 0.5
              method: '''every_point_interpolation'''
          output_transform: 'lambda x: (x[0], x[1])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/vehicle_registration/2110062123/best_model_23_loss=-0.8564.pt'''
    mode: '''test'''

predictor:
  module: flame.handlers.region_predictor
  class: RegionPredictor
  RegionPredictor:
    evaluator_name: '''engine'''
    output_dir: '''checkpoint/vehicle_registration/2110062123/best_model_23_loss=-0.8564/test/'''
    imsize: 416
    classes:
      DKX_BACK_TYPE_1: [[128, 0, 0], 0]
      DKX_TYPE_1: [[0, 128, 0], 1]
      DKX_BACK_TYPE_2: [[128, 128, 0], 2]
      DKX_TYPE_2: [[0, 0, 128], 3]
      DKX_BACK_TYPE_3: [[128, 0, 128], 4]
      DKX_TYPE_3: [[0, 128, 128], 5]
      DKX_BACK_TYPE_5: [[128, 128, 128], 6]
      DKX_FRONT_TYPE_5: [[64, 0, 0], 7]
    output_transform: 'lambda x: (x[0], x[-1])'

engine:
  module: flame.core.engine.evaluator
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
